sudo: false
language: java
jdk:
  - oraclejdk7
env:
  matrix:
    - ACCUMULO_VERSION='1.7.2'              ACCUMULO_API='1.7' HBASE_VERSION='1.2.1'		     HADOOP_VERSION='2.7.2'             GEOTOOLS_VERSION='14.2'   GEOSERVER_VERSION='2.8.2' PLATFORM_VERSION='""' BUILD_DOCS=false
   global:
    - secure: "TosKDl5mnt8UKeyWDg65i6cWENR7EorQbFPSvZ5ZfQfAaDAOeIN2OA/zxtRMELeYM82+n+GGXQOt0qPiYqyRlufYJJSUnWiwvI5gm3a8+f58atcU2R2bF9jd81bsL9jCS+JCQxAmzh8FCO6t7DJ4OdoMyMaIR7XjlSlsIJ97dd8="
    - secure: "IcwzKevdTSsKK9YERJ/LV81pfDe7Fx7qBxYcy43b0/emsioZJsJV5XSYHfFRIqceMkzp8LFBU8qiZR3cPZPKQoCjaG1QcwDeKQpyczIkMwzWzydhLR5dAzVETbQC9i2hH4sWjVVHW5WU6UUc3gCz5rPyIXFUYVUYxFeMWxHCe8w="
    - secure: "DdDzYhyJMMf6ZEIMe3FvK6IDWFWqWLbuFg8SCCnrAHpt6mGo8EOsvvbuyvvWqgCGsFZyvk+hJGamNjQEnSiBSP/2kwSUmpGgZ5DquHxFTkmTeh13ifqf231rwaCwBw9yrDXKdyMxHMVeHIXOjqV7Ylru2t2WoFxIEj4vHnqRjGQ="

cache:
  directories:
  - $HOME/.m2
  - test/landsat8
  - test/target/temp/gdal
install: "mvn -q clean install javadoc:aggregate -Dfindbugs.skip -Daccumulo.version=${ACCUMULO_VERSION} -Daccumulo.api=${ACCUMULO_API} -Dhbase.version=${HBASE_VERSION} -Dhadoop.version=${HADOOP_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -DskipITs=true -DskipTests=true -Dformatter.skip=true -P ${PLATFORM_VERSION}; .utility/build-docs-site.sh"
script: "travis_wait 80 mvn -q -T 2C verify -Daccumulo.version=${ACCUMULO_VERSION} -Daccumulo.api=${ACCUMULO_API} -Dhbase.version=${HBASE_VERSION} -Dhadoop.version=${HADOOP_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -P ${PLATFORM_VERSION}"
before_install:
  - export MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=192m -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"
  - chmod +x .utility/push-javadoc-to-gh-pages.sh
  - chmod +x .utility/build-docs-site.sh
  - chmod +x .utility/maven-coveralls-hack.sh
  - chmod +x .utility/changelog-generator.sh
  - .utility/maven-coveralls-hack.sh
  - cd dev-resources;mvn clean install;cd ..
after_success:
  - .utility/changelog-generator.sh
  - .utility/push-javadoc-to-gh-pages.sh
  - cd test; mvn coveralls:report -Daccumulo.version=${ACCUMULO_VERSION} -Daccumulo.api=${ACCUMULO_API} -Dhbase.version=${HBASE_VERSION} -Dhadoop.version=${HADOOP_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -P ${PLATFORM_VERSION}

addons:
  apt_packages:
    - pandoc
  coverity_scan:
    project:
      name: ngageoint/geowave
      description: Build submitted via Travis CI
    notification_email: GeoWave@nga.mil
    build_command_prepend: mvn clean
    build_command: mvn clean compile -Dfindbugs.skip -Daccumulo.version=${ACCUMULO_VERSION} -Daccumulo.api=${ACCUMULO_API} -Dhbase.version=${HBASE_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -DskipITs=true -DskipTests=true -Dformatter.skip=true -P ${PLATFORM_VERSION}
    branch_pattern: coverity_scan
